# ************************* 自定义配置 *************************
# *** 应用打包类型 ***
application.env: 1
# *** log自定义配置 ***
log:
  home: "/data/logs/mq-server"
  level: "debug"
# *** logback自定义配置 ***
spring.logback:
  access.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  error.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  info.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  application.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  sql.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  console.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  spring.logback.console.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  history.suffix: ".log"

# ************************* 第三方配置 *************************
# *** datasource配置 ***
spring:
  datasource:
    url: "jdbc:mysql://10.0.10.42/tc_message?autoReconnect=true&amp;failOverReadOnly=false&amp;maxReconnects=10&amp;characterEncoding=UTF8&amp;allowMultiQueries=true"
    username: "root"
    password: "shinemo123"
  redis:
    config: "10.0.10.53:6379:shinemo123:6"
# 日志格式中 clr 占位符生效配置
  output.ansi.enabled: "NEVER"
  jmx:
#    jmx 是否开启
    enabled: false
  http:
#      是否开启上传文件
    multipart:
      enabled: false
  mvc:
    formcontent:
#      是否接收 put 请求
      putfilter:
        enabled: false
  autoconfigure:
      exclude:
        - "org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration"
        - "org.springframework.boot.autoconfigure.websocket.WebSocketAutoConfiguration"
        - "org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration"
        - "org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration"
#        - "org.springframework.boot.autoconfigure.web.GsonHttpMessageConvertersConfiguration"
#        - "org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration"
#        - "org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration"
#        - "org.springframework.boot.autoconfigure.cache.SimpleCacheConfiguration"
#        - "org.springframework.boot.autoconfigure.cache.RedisCacheConfiguration"
#        - "org.springframework.boot.autoconfigure.cache.NoOpCacheConfiguration"
#        - "org.springframework.boot.autoconfigure.cache.GenericCacheConfiguration"



shinemo:
  application:
    domain: "http://app.e.uban360.net"
  jce:
    site-domain:
      yue-card: "http://10.0.14.11:60009"
    center-host: "10.0.10.62:16999"
    trace: true
    sample: 100
  mq:
    address: "10.0.10.86:9876"